apiVersion: batch/v1
kind: Job
metadata:
  name: terumoni-weather-job
spec:
  template:
    spec:
      containers:
        - image: asia.gcr.io/flex-k8s/terumoni-weather
          imagePullPolicy: Always
          name: terumoni-weather-container
          env:
            - name: WEATHER_API_URL
              valueFrom:
                  secretKeyRef:
                      name: openweather-config
                      key: url
            - name: WEATHER_API_KEY
              valueFrom:
                  secretKeyRef:
                      name: openweather-config
                      key: key
            - name: DB_HOST
              valueFrom:
                  secretKeyRef:
                      name: database-config
                      key: hostname
            - name: DB_USER
              valueFrom:
                  secretKeyRef:
                      name: database-config
                      key: username
            - name: DB_PASS
              valueFrom:
                  secretKeyRef:
                      name: database-config
                      key: password
            - name: DB_NAME
              value: "teruteru"
      restartPolicy: Never
